// hay 32 cartas en total


export const CARDS = [
    {
        id: 1,
        number:"1",
        title:"Abel",
        fileName:"Recurso 1.jpg",
        audioName:"pista1.mp3",
    },
    {
        id: 2,
        number:"2",
        title:"Arca del pacto",
        fileName:"Recurso 2.jpg",
        audioName:"pista2.mp3",
    },
    {
        id: 3,
        number:"3",
        title:"Dalila",
        fileName:"Recurso 3.jpg",
        audioName:"pista3.mp3",
    },
    {
        id: 4,
        number:"4",
        title:"David",
        fileName:"Recurso 4.jpg",
        audioName:"pista4.mp3",
    },
    {
        id: 5,
        number:"5",
        title:"Biblia",
        fileName:"Recurso 5.jpg",
        audioName:"pista5.mp3",
    },
    {
        id: 6,
        number:"6",
        title:"Daniel",
        fileName:"Recurso 6.jpg",
        audioName:"pista6.mp3",
    },
    {
        id: 7,
        number:"7",
        title:"El arca de Noé",
        fileName:"Recurso 7.jpg",
        audioName:"pista7.mp3",
    },
    {
        id: 8,
        number:"8",
        title:"Espíritu Santo",
        fileName:"Recurso 8.jpg",
        audioName:"pista8.mp3",
    },
    {
        id: 9,
        number:"9",
        title:"Eva",
        fileName:"Recurso 9.jpg",
        audioName:"pista9.mp3",
    },
    {
        id: 10,
        number:"10",
        title:"Faraón",
        fileName:"Recurso 10.jpg",
        audioName:"pista10.mp3",
    },
    {
        id: 11,
        number:"11",
        title:"Gedeón",
        fileName:"Recurso 11.jpg",
        audioName:"pista11.mp3",
    },
    {
        id: 12,
        number:"12",
        title:"Goliat",
        fileName:"Recurso 12.jpg",
        audioName:"pista12.mp3",
    },
    {
        id: 13,
        number:"13",
        title:"Jesús",
        fileName:"Recurso 13.jpg",
        audioName:"pista13.mp3",
    },
    {
        id: 14,
        number:"14",
        title:"Jonás",
        fileName:"Recurso 14.jpg",
        audioName:"pista14.mp3",
    },
    {
        id: 15,
        number:"15",
        title:"José",
        fileName:"Recurso 15.jpg",
        audioName:"pista15.mp3",
    },
    {
        id: 16,
        number:"16",
        title:"Judas I.",
        fileName:"Recurso 16.jpg",
        audioName:"pista16.mp3",
    },
    {
        id: 17,
        number:"17",
        title:"Malaquías",
        fileName:"Recurso 17.jpg",
        audioName:"pista17.mp3",
    },
    {
        id: 18,
        number:"18",
        title:"María",
        fileName:"Recurso 18.jpg",
        audioName:"pista18.mp3",
    },
    {
        id: 19,
        number:"19",
        title:"Moisés",
        fileName:"Recurso 19.jpg",
        audioName:"pista19.mp3",
    },
    {
        id: 20,
        number:"20",
        title:"Noé",
        fileName:"Recurso 20.jpg",
        audioName:"pista20.mp3",
    },
    {
        id: 21,
        number:"21",
        title:"Pablo",
        fileName:"Recurso 21.jpg",
        audioName:"pista21.mp3",
    },
    {
        id: 22,
        number:"22",
        title:"Pedro",
        fileName:"Recurso 22.jpg",
        audioName:"pista22.mp3",
    },
    {
        id: 23,
        number:"23",
        title:"Ruth",
        fileName:"Recurso 23.jpg",
        audioName:"pista23.mp3",
    },
    {
        id: 24,
        number:"24",
        title:"Salomón",
        fileName:"Recurso 24.jpg",
        audioName:"pista24.mp3",
    },
    {
        id: 25,
        number:"25",
        title:"Samuel",
        fileName:"Recurso 25.jpg",
        audioName:"pista25.mp3",
    },
    {
        id: 26,
        number:"26",
        title:"Sansón",
        fileName:"Recurso 26.jpg",
        audioName:"pista26.mp3",
    },
    {
        id: 27,
        number:"27",
        title:"Sara",
        fileName:"Recurso 27.jpg",
        audioName:"pista27.mp3",
    },
    {
        id: 28,
        number:"28",
        title:"Saúl",
        fileName:"Recurso 28.jpg",
        audioName:"pista28.mp3",
    },
    {
        id: 29,
        number:"29",
        title:"Simón",
        fileName:"Recurso 29.jpg",
        audioName:"pista29.mp3",
    },
    {
        id: 30,
        number:"30",
        title:"Thomas",
        fileName:"Recurso 30.jpg",
        audioName:"pista30.mp3",
    },
    {
        id: 31,
        number:"31",
        title:"El burrito",
        fileName:"Recurso 31.jpg",
        audioName:"pista31.mp3",
    },
    {
        id: 32,
        number:"32",
        title:"La oveja",
        fileName:"Recurso 32.jpg",
        audioName:"pista32.mp3",
    },
];

